server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_db
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/db-changelog.xml  # Update with your Liquibase change log file location


